title: Your awesome title
author: David Pérez Cabrera
email: dperezcabrera@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
 Curso de github-pages with jekyll

# social links
twitter_username: dperezcabrera # DO NOT include the @ character, or else the build will fail!
github_username:  dperezcabrera # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
